#!/bin/bash

if [ "${1}" != "configure" ]; then
  exit 0
fi

adduser \
  --system \
  --home /var/lib/@SYSTEM_USER@ \
  --shell /usr/sbin/nologin \
  --quiet \
  --group \
  @SYSTEM_USER@ || true

mkdir -p @CMAKE_INSTALL_LOCALSTATEDIR@/log/nxdn
chown -R @SYSTEM_USER@:adm @CMAKE_INSTALL_LOCALSTATEDIR@/log/nxdn
chmod -R 02755 @CMAKE_INSTALL_LOCALSTATEDIR@/log/nxdn

for F in @CMAKE_INSTALL_SYSCONFDIR@/*.ini; do
  if [ ! -e "${F}-vanilla" ]; then
    cp "${F}" "${F}-vanilla"
  fi
done

chown -R @SYSTEM_USER@:@SYSTEM_USER@ /var/lib/@SYSTEM_USER@
chmod -R 0644 /var/lib/@SYSTEM_USER@/*

chown -R root:@SYSTEM_USER@ @CMAKE_INSTALL_SYSCONFDIR@
chmod 0755 @CMAKE_INSTALL_SYSCONFDIR@
chmod 0644 @CMAKE_INSTALL_SYSCONFDIR@/*

systemctl daemon-reload
